services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER:-semaphore}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME:-semaphore}
    volumes:
      - semaphore-postgres:/var/lib/postgresql/data
    restart: unless-stopped

  semaphore:
    image: semaphoreui/semaphore:latest
    ports:
      - "${HOST_PORT:-80}:3000"
    dns:
      - ${LOCAL_DNS}
    environment:
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB_HOST: postgres
      SEMAPHORE_DB_PORT: ${DB_PORT:-5432}
      SEMAPHORE_DB: ${DB_NAME:-semaphore}
      SEMAPHORE_DB_USER: ${DB_USER:-semaphore}
      SEMAPHORE_DB_PASS: ${DB_PASS}
      SEMAPHORE_ADMIN_PASSWORD: ${ADMIN_PASS}
      SEMAPHORE_ADMIN_NAME: ${ADMIN_NAME}
      SEMAPHORE_ADMIN_EMAIL: ${ADMIN_EMAIL}
      SEMAPHORE_ADMIN: ${ADMIN_USER}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY_ENCRYPTION}

      # SMTP Configuration
      SEMAPHORE_EMAIL_ALERT: ${SMTP_EMAIL_ALERT:-false}
      SEMAPHORE_EMAIL_SECURE: ${SMTP_SECURE:-true}
      SEMAPHORE_EMAIL_HOST: ${SMTP_HOST}
      SEMAPHORE_EMAIL_PORT: ${SMTP_PORT}
      SEMAPHORE_EMAIL_SENDER: ${SMTP_SENDER}
      SEMAPHORE_EMAIL_USERNAME: ${SMTP_USER:-}
      SEMAPHORE_EMAIL_PASSWORD: ${SMTP_PASS:-}

      # Telegram Configuration
      SEMAPHORE_TELEGRAM_ALERT: "${TELEGRAM_ALERT:-false}"
      SEMAPHORE_TELEGRAM_TOKEN: "${TELEGRAM_TOKEN:-}"
      SEMAPHORE_TELEGRAM_CHAT: "${TELEGRAM_CHAT_ID:-}"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  semaphore-postgres:
